### ISSUE TITLE
Onyx Files

### ISSUE THREAD

**Issue by DavyA** [AOSPA/android_vendor_pa#19]
Hi,
There aren't onyx folder and its files inside, in products directory, even if it is a officil device.

Can You add them?

Thanks

**Comment by TheCrazyLex** [comment]
For me the folder is there

**Comment by DavyA** [comment]
If you are talking about repo called android_device_oneplus_onyx there is, but it hasn't pa_onyx.mk, and it isn't even in vendor pa.

**Comment by TheCrazyLex** [comment]
It is, check the marshmallow-caf branch

**Comment by DavyA** [comment]
Oh sorry.
Thanks a lot ;)
